language: node_js
node_js:
- 8
os:
- linux
- osx
- window
before_install:
- git clone https://github.com/Genuifx/wxa-cli.git;
- cd wxa-cli && npm i && npm run travis-dev;
- npm link;
- cd .. && wxa create base h && cd h;
install:
- npm i
script: wxa build
